server:
  port: 10000
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  

logging:
    level:
      william.cs.admin.server: INFO

#spring:
#  security:
#    user:
#      name: "springboot_admin"
#      password: "springboot_password"
      
